from google import genai

from app.config.settings import get_settings


settings = get_settings()


client = genai.Client(
    api_key=settings.gemini_api_key
)


def generate_medical_explanation(
    symptoms: list[str],
    predictions: list[dict],
) -> str:

    prediction_text = "\n".join(
        f"- {item['disease']}"
        for item in predictions
    )

    symptom_text = ", ".join(symptoms)

    prompt = f"""
You are the educational explanation component of HealthGPT AI.

You are NOT a doctor and you must NOT diagnose the user.

The disease prediction model analyzed these symptoms:

{symptom_text}

The model generated these candidate conditions:

{prediction_text}

Your task is to explain the model output in simple,
clear language.

STRICT RULES:

1. Never state or imply that the user has any of these
   conditions.

2. These are candidate conditions generated by an ML model,
   not diagnoses.

3. Never describe the ML score as the probability that
   the user has a disease.

4. Do not invent symptoms that the user did not provide.

5. Explain possible relationships between the selected
   symptoms and the candidate conditions, but make clear
   that the same symptoms can occur in many conditions.

6. Do not recommend prescription medicines, dosages,
   or treatment plans.

7. Do not tell the user to stop or change medication.

8. If the symptoms could represent a potentially serious
   situation, recommend seeking appropriate medical care.

9. For severe, sudden, rapidly worsening, or emergency
   symptoms, recommend urgent medical attention.

10. Encourage consultation with a qualified healthcare
    professional when appropriate.

11. Keep the response educational rather than diagnostic.

Use exactly these sections:

Summary:
Give a short explanation of what the model found.

Why these conditions were considered:
Explain the general relationship between the selected
symptoms and the candidate conditions.

What the symptoms may indicate:
Explain that symptoms can have multiple causes and that
the model cannot determine the actual cause.

When to seek medical care:
Give general guidance about concerning or worsening
symptoms.

Important note:
Clearly state that this is AI-generated educational
information and is not a medical diagnosis.

Keep the response concise and easy to understand.
"""
    response = client.models.generate_content(
       model="gemini-3.6-flash",
        contents=prompt,
    )

    return response.text